version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: url_shortener_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: url_shortener_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: url_shortener_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: postgres
      REDIS_HOST: redis
      JWT_SECRET: super-secret-resume-project-jwt-token
    depends_on:
      - postgres
      - redis

  worker:
    build: ./backend
    container_name: url_shortener_worker
    restart: unless-stopped
    command: npm run worker
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: url_shortener_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg_data:
